apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  selector:
    matchLabels:
      app: bot-app
  template:
    metadata:
      labels:
        app: bot-app
    spec:
      containers:
        - name: bot-app
          image: yoryuuuuu/tutti:0.2
          envFrom:
            - secretRef:
                name: bot-secret
