apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  selector:
    matchLabels:
      app: bot-app
  template:
    metadata:
      labels:
        app: bot-app
    spec:
      containers:
        - name: bot-app
          image: yoryuuuuu/tutti:0.2
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: bot-secret
